<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Center of buoyancy -->
    <xacro:property name="hrov_cob" value="0 0 0.06"/>

    <!-- Vehicle's actual volume (Gazebo cannot compute the volume out of the mesh) -->
    <xacro:property name="hrov_volume" value="0.06799987704121499"/>

    <!-- Describing the dimensions of the vehicle's bounding box -->
    <xacro:property name="hrov_length" value="1.98"/>
    <xacro:property name="hrov_width"  value="0.115"/>
    <xacro:property name="hrov_height" value="0.115"/>
    <xacro:property name="hrov_radius" value="${0.5 * hrov_width}"/>

    <xacro:macro name="hrov_hydro_model" params="namespace">
      <!-- List of hydrodynamic models this robot's links -->
      <link name="${namespace}/base_link">
        <!-- This flag will make the link neutrally buoyant -->
        <neutrally_buoyant>0</neutrally_buoyant>

        <!-- Link's volume -->
        <volume>${hrov_volume}</volume>

        <!-- Link's bounding box, it is used to recalculate the immersed
        volume when close to the surface.
        This is a workaround the invalid bounding box given by Gazebo-->
        <box>
          <width>${hrov_width}</width>
          <length>${hrov_length}</length>
          <height>${hrov_height}</height>
        </box>

        <!-- Center of buoyancy -->
        <center_of_buoyancy>${hrov_cob}</center_of_buoyancy>

        <!--
        Choose one of the hydrodynamic models below, all are based on
        Fossen's equation of motion for underwater vehicles

        Reference:
        [1] Fossen, Thor I. Handbook of marine craft hydrodynamics and motion
            control. John Wiley & Sons, 2011.
        -->

        <!-- 1) Fossen's equation of motion -->
        <hydrodynamic_model>
          <type>fossen</type>
          <added_mass>
            4   0   0   0   0   0
              0   95  0   0   0   0
              0   0   75  0   0   0
              0   0   0   0.4 0   0
              0   0   0   0   27  0
              0   0   0   0   0   32
          </added_mass>
          <!--
            The linear damping coefficients can be provided as a diagonal (6 elements)
            or a full matrix (36 coefficients), like the added-mass coefficients above
          -->
          <linear_damping_forward_speed>
            -8      0       0       0       0       0
              0       -162    0       0       0       150
              0       0       -108    0       -100    0
              0       0       0       -13     0       0
              0       0       37      0       -20     0
              0       -34     0       0       0       -32
          </linear_damping_forward_speed>
          <!--
            The linear damping coefficients proportional to the forward speed
            can be provided as a diagonal (6 elements) or a full matrix (36 coefficients),
            like the added-mass coefficients above.
            This matrix is mostly useful for slender bodies (e.g. AUVs with torpedo shape)
          -->
          <!--linear_damping_forward_speed>
            0 0 0 0 0 0
          </linear_damping_forward_speed-->
          <!--
            The quadratic damping coefficients can be provided as a diagonal (6 elements)
            or a full matrix (36 coefficients), like the added-mass coefficients above
          -->
          <!--quadratic_damping>
            -2.4   0      0      0       0      0
                0      -80    0      0       0      0.3
                0      0      -80    0       -0.3   0
                0      0      0      -0.0006 0      0
                0      0      1.5    0       -9.1   0
                0      -1.5   0      0       0      -9.1
          </quadratic_damping-->

          <!--
            In case you want to model a simple surface vessel, you can use the
            implementation of linear (small angle) theory for boxed shaped vessels
            by providing the following parameters. If you omit the area of the
            water level plane area, it will be calculated from the bounding box
            parameters. Uncomment the lines below in case you are simulating a
            surface vessel.
            For more details on these parameters and the computation of buoyancy
            for vessels using this theory, check:
              [1] Lecture Notes  TTK 4190 Guidance and Control of Vehicles (T. I. Fossen)
                  http://www.fossen.biz/wiley/Ch4.pdf
              [2] Fossen, Thor I. Handbook of marine craft hydrodynamics and motion
                  control. John Wiley & Sons, 2011.
          -->

          <!--
          <metacentric_width>0.0</metacentric_width>
          <metacentric_length>0.0</metacentric_length>
          <submerged_height>0.0</submerged_height>
          -->
        </hydrodynamic_model>

        <!-- 2) This computes the added-mass and damping parameters for a sphere
        in the fluid with the given radius -->
        <!--hydrodynamic_model>
          <type>sphere</type>
          <radius>0</radius>
        </hydrodynamic_model-->

      </link>
    </xacro:macro>

</robot>
